### ISSUE TITLE
Support for motion/temperature sensors

### ISSUE THREAD

**Issue by apexad** [kundk-ckret/homebridge-lightify-api#2]
Lightify now supports zigbee motion/temperature sensors:
https://www.sylvania.com/en-us/products/new-products/Pages/LIGHTIFY®-Smart-Sensor.aspx
https://www.amazon.com/Sylvania-Lightify-Motion-Temperature-Sensor/
https://m.lowes.com/pd/Iris-Motion-Sensor-Works-with-Iris/999925310

They detect motion and also report the temperature. It would be great if you could add them to this plugin for homebridge.

**Comment by kundk-ckret** [comment]
It seems they are not yet available in Germany yet, so I couldn't get my hands on them yet.

But to be honest - I'm not sure, if they'd work well or at all with homebridge, because of the way they interact. At the moment, homebridge is the "master" and talks to the bulbs via the hub.
For the sensors, it would need to be the other way around in order to support events like "motion detected"... Or they'd need to get queried all the time which would drain the batteries... :/
